/**
 * SPDX-License-Identifier: Apache-2.0
 */
import type { SettlementRuntimeKey } from '@agroasys/sdk';

export interface GatewayConfig {
  port: number;
  dbHost: string;
  dbPort: number;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  dbMigrationUser?: string;
  dbMigrationPassword?: string;
  dbSslMode?: 'disable' | 'require' | 'verify-full';
  authBaseUrl: string;
  authRequestTimeoutMs: number;
  indexerGraphqlUrl: string;
  indexerRequestTimeoutMs: number;
  rpcUrl: string;
  rpcFallbackUrls: string[];
  rpcReadTimeoutMs: number;
  rpcQuorum?: number;
  chainId: number;
  escrowAddress: string;
  usdcAddress: string;
  settlementRuntimeKey?: SettlementRuntimeKey;
  networkName?: string;
  explorerBaseUrl?: string | null;
  contractAddressRequired: boolean;
  operatorSignerEnvironment?: string;
  enableMutations: boolean;
  writeAllowlist: string[];
  governanceQueueTtlSeconds: number;
  settlementIngressEnabled: boolean;
  immediateInspectionAcceptanceEnabled?: boolean;
  settlementServiceAuthApiKeysJson: string;
  settlementServiceAuthSharedSecret?: string;
  settlementServiceAuthMaxSkewSeconds: number;
  settlementServiceAuthNonceTtlSeconds: number;
  settlementCallbackEnabled: boolean;
  settlementCallbackUrl?: string;
  settlementCallbackApiKey?: string;
  settlementCallbackApiSecret?: string;
  settlementCallbackRequestTimeoutMs: number;
  settlementCallbackPollIntervalMs: number;
  settlementCallbackMaxAttempts: number;
  settlementCallbackInitialBackoffMs: number;
  settlementCallbackMaxBackoffMs: number;
  idempotencyLeaseDurationMs?: number;
  gaslessExecutionEnabled?: boolean;
  gaslessExecutorPrivateKey?: string;
  gaslessSignerCustodyMode?: 'raw_private_key' | 'kms' | 'mpc';
  gaslessManagedSignerUrl?: string;
  gaslessManagedSignerApiKey?: string;
  gaslessManagedSignerRequestTimeoutMs?: number;
  gaslessBroadcastPaused?: boolean;
  gaslessMaxGasLimit?: bigint;
  gaslessMaxFeePerGasWei?: bigint;
  gaslessMaxNativeCostWei?: bigint;
  gaslessMinExecutorBalanceWei?: bigint;
  gaslessLowBalanceAlertWei?: bigint;
  gaslessCapacityTargetTxPerDay?: number;
  gaslessCapacityBurstMultiplierBasisPoints?: number;
  gaslessCapacitySafetyMarginBasisPoints?: number;
  gaslessCapacityRequiredExecutorBalanceWei?: bigint;
  gaslessCapacityFailClosed?: boolean;
  gaslessRequestMaxTtlSeconds?: number;
  gaslessStuckQueueThresholdMs?: number;
  gaslessReceiptTimeoutMs?: number;
  gaslessOutcomeReconciliationIntervalMs?: number;
  gaslessRepeatedFailureAlertThreshold?: number;
  gaslessCommandLeaseMs?: number;
  gaslessCommandPollIntervalMs?: number;
  gaslessCommandRetryInitialMs?: number;
  gaslessCommandRetryMaxMs?: number;
  gaslessCommandWaitTimeoutMs?: number;
  gaslessCommandMaxAttempts?: number;
  gaslessCommandMaxBatch?: number;
  gaslessCommandMaxPending?: number;
  gaslessRequireRpcFallback?: boolean;
  oracleBaseUrl?: string;
  oracleServiceApiKey?: string;
  oracleServiceApiSecret?: string;
  treasuryBaseUrl?: string;
  treasuryServiceApiKey?: string;
  treasuryServiceApiSecret?: string;
  reconciliationBaseUrl?: string;
  ricardianBaseUrl?: string;
  ricardianServiceApiKey?: string;
  ricardianServiceApiSecret?: string;
  notificationsBaseUrl?: string;
  downstreamReadRetryBudget?: number;
  downstreamMutationRetryBudget?: number;
  downstreamReadTimeoutMs?: number;
  downstreamMutationTimeoutMs?: number;
  corsAllowedOrigins: string[];
  corsAllowNoOrigin: boolean;
  rateLimitEnabled: boolean;
  rateLimitRedisUrl?: string;
  rateLimitFailOpen?: boolean;
  allowInsecureDownstreamAuth: boolean;
  commitSha: string;
  buildTime: string;
  nodeEnv: string;
}
