/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUSDCReceiveWithAuthorization,
  IUSDCReceiveWithAuthorizationInterface,
} from "../../../src/AgroasysEscrow.sol/IUSDCReceiveWithAuthorization";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validAfter",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validBefore",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "nonce",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "receiveWithAuthorization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUSDCReceiveWithAuthorization__factory {
  static readonly abi = _abi;
  static createInterface(): IUSDCReceiveWithAuthorizationInterface {
    return new Interface(_abi) as IUSDCReceiveWithAuthorizationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUSDCReceiveWithAuthorization {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUSDCReceiveWithAuthorization;
  }
}
