/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgroasysEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_PROPOSAL_TTL"
      | "DISPUTE_WINDOW"
      | "GOVERNANCE_PROPOSAL_TTL"
      | "IN_TRANSIT_TIMEOUT"
      | "LOCK_TIMEOUT"
      | "adminAddCounter"
      | "adminAddHasApproved"
      | "adminAddProposalCancelled"
      | "adminAddProposalExpiresAt"
      | "adminAddProposals"
      | "admins"
      | "approveAddAdmin"
      | "approveDisputeSolution"
      | "approveOracleUpdate"
      | "approveUnpause"
      | "cancelExpiredAddAdminProposal"
      | "cancelExpiredDisputeProposal"
      | "cancelExpiredOracleUpdateProposal"
      | "cancelLockedTradeAfterTimeout"
      | "cancelUnpauseProposal"
      | "claim"
      | "claimableUsdc"
      | "confirmArrival"
      | "createTrade"
      | "disableOracleEmergency"
      | "disputeCounter"
      | "disputeHasApproved"
      | "disputeProposalCancelled"
      | "disputeProposalExpiresAt"
      | "disputeProposals"
      | "executeAddAdmin"
      | "executeOracleUpdate"
      | "finalizeAfterDisputeWindow"
      | "getBuyerNonce"
      | "getNextTradeId"
      | "governanceApprovals"
      | "governanceTimelock"
      | "hasActiveUnpauseProposal"
      | "inTransitSince"
      | "isAdmin"
      | "nonces"
      | "openDispute"
      | "oracleActive"
      | "oracleAddress"
      | "oracleUpdateCounter"
      | "oracleUpdateHasApproved"
      | "oracleUpdateProposalCancelled"
      | "oracleUpdateProposalExpiresAt"
      | "oracleUpdateProposals"
      | "pause"
      | "paused"
      | "proposeAddAdmin"
      | "proposeDisputeSolution"
      | "proposeOracleUpdate"
      | "proposeUnpause"
      | "refundInTransitAfterTimeout"
      | "releaseFundsStage1"
      | "requiredApprovals"
      | "totalClaimableUsdc"
      | "tradeActiveDisputeProposalId"
      | "tradeCounter"
      | "tradeHasActiveDisputeProposal"
      | "trades"
      | "treasuryAddress"
      | "unpauseHasApproved"
      | "unpauseProposal"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAddApproved"
      | "AdminAddProposalExpiredCancelled"
      | "AdminAddProposed"
      | "AdminAdded"
      | "ArrivalConfirmed"
      | "ClaimableAccrued"
      | "Claimed"
      | "DisputeApproved"
      | "DisputeFinalized"
      | "DisputeOpenedByBuyer"
      | "DisputePayout"
      | "DisputeProposalExpiredCancelled"
      | "DisputeSolutionProposed"
      | "FinalTrancheReleased"
      | "FundsReleasedStage1"
      | "FundsReleasedStage2"
      | "InTransitTimeoutRefunded"
      | "OracleDisabledEmergency"
      | "OracleUpdateApproved"
      | "OracleUpdateProposalExpiredCancelled"
      | "OracleUpdateProposed"
      | "OracleUpdated"
      | "Paused"
      | "PlatformFeesPaidStage1"
      | "TradeCancelledAfterLockTimeout"
      | "TradeLocked"
      | "UnpauseApproved"
      | "UnpauseProposalCancelled"
      | "UnpauseProposed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_PROPOSAL_TTL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_PROPOSAL_TTL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IN_TRANSIT_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddHasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddProposalCancelled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddProposalExpiresAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAddAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveDisputeSolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOracleUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelExpiredAddAdminProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelExpiredDisputeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelExpiredOracleUpdateProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelLockedTradeAfterTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelUnpauseProposal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimableUsdc",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmArrival",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrade",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disableOracleEmergency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeHasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposalCancelled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposalExpiresAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAddAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOracleUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAfterDisputeWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextTradeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveUnpauseProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inTransitSince",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleUpdateCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleUpdateHasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleUpdateProposalCancelled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleUpdateProposalExpiresAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleUpdateProposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeAddAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeDisputeSolution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOracleUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundInTransitAfterTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFundsStage1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimableUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradeActiveDisputeProposalId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradeHasActiveDisputeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseHasApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseProposal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_PROPOSAL_TTL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_PROPOSAL_TTL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IN_TRANSIT_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddHasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddProposalCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddProposalExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAddAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveDisputeSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOracleUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelExpiredAddAdminProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelExpiredDisputeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelExpiredOracleUpdateProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelLockedTradeAfterTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelUnpauseProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmArrival",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableOracleEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeHasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposalCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposalExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAddAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOracleUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAfterDisputeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveUnpauseProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inTransitSince",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleUpdateCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleUpdateHasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleUpdateProposalCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleUpdateProposalExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleUpdateProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeAddAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeDisputeSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeOracleUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundInTransitAfterTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFundsStage1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeActiveDisputeProposalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeHasActiveDisputeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseHasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace AdminAddApprovedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    approver: string,
    approvalCount: bigint,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    approver: string;
    approvalCount: bigint;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminAddProposalExpiredCancelledEvent {
  export type InputTuple = [proposalId: BigNumberish, cancelledBy: AddressLike];
  export type OutputTuple = [proposalId: bigint, cancelledBy: string];
  export interface OutputObject {
    proposalId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminAddProposedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    newAdmin: AddressLike,
    eta: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    newAdmin: string,
    eta: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    newAdmin: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminAddedEvent {
  export type InputTuple = [newAdmin: AddressLike];
  export type OutputTuple = [newAdmin: string];
  export interface OutputObject {
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArrivalConfirmedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    arrivalTimestamp: BigNumberish
  ];
  export type OutputTuple = [tradeId: bigint, arrivalTimestamp: bigint];
  export interface OutputObject {
    tradeId: bigint;
    arrivalTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimableAccruedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    claimType: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    recipient: string,
    amount: bigint,
    claimType: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    recipient: string;
    amount: bigint;
    claimType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [claimant: AddressLike, amount: BigNumberish];
  export type OutputTuple = [claimant: string, amount: bigint];
  export interface OutputObject {
    claimant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeApprovedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    approver: string,
    approvalCount: bigint,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    approver: string;
    approvalCount: bigint;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeFinalizedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    tradeId: BigNumberish,
    disputeStatus: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    tradeId: bigint,
    disputeStatus: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    tradeId: bigint;
    disputeStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedByBuyerEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputePayoutEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    proposalId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    payoutType: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    proposalId: bigint,
    recipient: string,
    amount: bigint,
    payoutType: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    proposalId: bigint;
    recipient: string;
    amount: bigint;
    payoutType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeProposalExpiredCancelledEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    tradeId: BigNumberish,
    cancelledBy: AddressLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    tradeId: bigint,
    cancelledBy: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    tradeId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeSolutionProposedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    tradeId: BigNumberish,
    disputeStatus: BigNumberish,
    proposer: AddressLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    tradeId: bigint,
    disputeStatus: bigint,
    proposer: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    tradeId: bigint;
    disputeStatus: bigint;
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalTrancheReleasedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    supplier: AddressLike,
    supplierSecondTranche: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    supplier: string,
    supplierSecondTranche: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    supplier: string;
    supplierSecondTranche: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedStage1Event {
  export type InputTuple = [
    tradeId: BigNumberish,
    supplier: AddressLike,
    supplierFirstTranche: BigNumberish,
    treasury: AddressLike,
    logisticsAmount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    supplier: string,
    supplierFirstTranche: bigint,
    treasury: string,
    logisticsAmount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    supplier: string;
    supplierFirstTranche: bigint;
    treasury: string;
    logisticsAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedStage2Event {
  export type InputTuple = [
    tradeId: BigNumberish,
    supplier: AddressLike,
    supplierSecondTranche: BigNumberish,
    treasury: AddressLike,
    platformFeesAmount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    supplier: string,
    supplierSecondTranche: bigint,
    treasury: string,
    platformFeesAmount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    supplier: string;
    supplierSecondTranche: bigint;
    treasury: string;
    platformFeesAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InTransitTimeoutRefundedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    refundedAmount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    refundedAmount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    refundedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleDisabledEmergencyEvent {
  export type InputTuple = [by: AddressLike, previousOracle: AddressLike];
  export type OutputTuple = [by: string, previousOracle: string];
  export interface OutputObject {
    by: string;
    previousOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdateApprovedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    approver: string,
    approvalCount: bigint,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    approver: string;
    approvalCount: bigint;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdateProposalExpiredCancelledEvent {
  export type InputTuple = [proposalId: BigNumberish, cancelledBy: AddressLike];
  export type OutputTuple = [proposalId: bigint, cancelledBy: string];
  export interface OutputObject {
    proposalId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdateProposedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    newOracle: AddressLike,
    eta: BigNumberish,
    emergencyFastTrack: boolean
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    newOracle: string,
    eta: bigint,
    emergencyFastTrack: boolean
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    newOracle: string;
    eta: bigint;
    emergencyFastTrack: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeesPaidStage1Event {
  export type InputTuple = [
    tradeId: BigNumberish,
    treasury: AddressLike,
    platformFeesAmount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    treasury: string,
    platformFeesAmount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    treasury: string;
    platformFeesAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCancelledAfterLockTimeoutEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    refundedAmount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    refundedAmount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    refundedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeLockedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    supplier: AddressLike,
    totalAmount: BigNumberish,
    logisticsAmount: BigNumberish,
    platformFeesAmount: BigNumberish,
    supplierFirstTranche: BigNumberish,
    supplierSecondTranche: BigNumberish,
    ricardianHash: BytesLike
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    supplier: string,
    totalAmount: bigint,
    logisticsAmount: bigint,
    platformFeesAmount: bigint,
    supplierFirstTranche: bigint,
    supplierSecondTranche: bigint,
    ricardianHash: string
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    supplier: string;
    totalAmount: bigint;
    logisticsAmount: bigint;
    platformFeesAmount: bigint;
    supplierFirstTranche: bigint;
    supplierSecondTranche: bigint;
    ricardianHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauseApprovedEvent {
  export type InputTuple = [
    approver: AddressLike,
    approvalCount: BigNumberish,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    approver: string,
    approvalCount: bigint,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    approver: string;
    approvalCount: bigint;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauseProposalCancelledEvent {
  export type InputTuple = [cancelledBy: AddressLike];
  export type OutputTuple = [cancelledBy: string];
  export interface OutputObject {
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauseProposedEvent {
  export type InputTuple = [proposer: AddressLike];
  export type OutputTuple = [proposer: string];
  export interface OutputObject {
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgroasysEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AgroasysEscrow;
  waitForDeployment(): Promise<this>;

  interface: AgroasysEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_PROPOSAL_TTL: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  GOVERNANCE_PROPOSAL_TTL: TypedContractMethod<[], [bigint], "view">;

  IN_TRANSIT_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  LOCK_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  adminAddCounter: TypedContractMethod<[], [bigint], "view">;

  adminAddHasApproved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  adminAddProposalCancelled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  adminAddProposalExpiresAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  adminAddProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, string] & {
        newAdmin: string;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        eta: bigint;
        proposer: string;
      }
    ],
    "view"
  >;

  admins: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approveAddAdmin: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveDisputeSolution: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveOracleUpdate: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveUnpause: TypedContractMethod<[], [void], "nonpayable">;

  cancelExpiredAddAdminProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelExpiredDisputeProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelExpiredOracleUpdateProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelLockedTradeAfterTimeout: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelUnpauseProposal: TypedContractMethod<[], [void], "nonpayable">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimableUsdc: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  confirmArrival: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTrade: TypedContractMethod<
    [
      _supplier: AddressLike,
      _totalAmount: BigNumberish,
      _logisticsAmount: BigNumberish,
      _platformFeesAmount: BigNumberish,
      _supplierFirstTranche: BigNumberish,
      _supplierSecondTranche: BigNumberish,
      _ricardianHash: BytesLike,
      _buyerNonce: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  disableOracleEmergency: TypedContractMethod<[], [void], "nonpayable">;

  disputeCounter: TypedContractMethod<[], [bigint], "view">;

  disputeHasApproved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  disputeProposalCancelled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  disputeProposalExpiresAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  disputeProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, bigint, string] & {
        tradeId: bigint;
        disputeStatus: bigint;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        proposer: string;
      }
    ],
    "view"
  >;

  executeAddAdmin: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeOracleUpdate: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeAfterDisputeWindow: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBuyerNonce: TypedContractMethod<[buyer: AddressLike], [bigint], "view">;

  getNextTradeId: TypedContractMethod<[], [bigint], "view">;

  governanceApprovals: TypedContractMethod<[], [bigint], "view">;

  governanceTimelock: TypedContractMethod<[], [bigint], "view">;

  hasActiveUnpauseProposal: TypedContractMethod<[], [boolean], "view">;

  inTransitSince: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  isAdmin: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  openDispute: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  oracleActive: TypedContractMethod<[], [boolean], "view">;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  oracleUpdateCounter: TypedContractMethod<[], [bigint], "view">;

  oracleUpdateHasApproved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  oracleUpdateProposalCancelled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  oracleUpdateProposalExpiresAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  oracleUpdateProposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, string, boolean] & {
        newOracle: string;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        eta: bigint;
        proposer: string;
        emergencyFastTrack: boolean;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proposeAddAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  proposeDisputeSolution: TypedContractMethod<
    [_tradeId: BigNumberish, _disputeStatus: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proposeOracleUpdate: TypedContractMethod<
    [_newOracle: AddressLike],
    [bigint],
    "nonpayable"
  >;

  proposeUnpause: TypedContractMethod<[], [boolean], "nonpayable">;

  refundInTransitAfterTimeout: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseFundsStage1: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  totalClaimableUsdc: TypedContractMethod<[], [bigint], "view">;

  tradeActiveDisputeProposalId: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  tradeCounter: TypedContractMethod<[], [bigint], "view">;

  tradeHasActiveDisputeProposal: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tradeId: bigint;
        ricardianHash: string;
        status: bigint;
        buyerAddress: string;
        supplierAddress: string;
        totalAmountLocked: bigint;
        logisticsAmount: bigint;
        platformFeesAmount: bigint;
        supplierFirstTranche: bigint;
        supplierSecondTranche: bigint;
        createdAt: bigint;
        arrivalTimestamp: bigint;
      }
    ],
    "view"
  >;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  unpauseHasApproved: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  unpauseProposal: TypedContractMethod<
    [],
    [
      [bigint, boolean, bigint, string] & {
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        proposer: string;
      }
    ],
    "view"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_PROPOSAL_TTL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_PROPOSAL_TTL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IN_TRANSIT_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminAddCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminAddHasApproved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "adminAddProposalCancelled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "adminAddProposalExpiresAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminAddProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, string] & {
        newAdmin: string;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        eta: bigint;
        proposer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approveAddAdmin"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveDisputeSolution"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveOracleUpdate"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelExpiredAddAdminProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelExpiredDisputeProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelExpiredOracleUpdateProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelLockedTradeAfterTimeout"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelUnpauseProposal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableUsdc"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confirmArrival"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTrade"
  ): TypedContractMethod<
    [
      _supplier: AddressLike,
      _totalAmount: BigNumberish,
      _logisticsAmount: BigNumberish,
      _platformFeesAmount: BigNumberish,
      _supplierFirstTranche: BigNumberish,
      _supplierSecondTranche: BigNumberish,
      _ricardianHash: BytesLike,
      _buyerNonce: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableOracleEmergency"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeHasApproved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputeProposalCancelled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputeProposalExpiresAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, bigint, string] & {
        tradeId: bigint;
        disputeStatus: bigint;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        proposer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeAddAdmin"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeOracleUpdate"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeAfterDisputeWindow"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyerNonce"
  ): TypedContractMethod<[buyer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextTradeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "governanceApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "governanceTimelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasActiveUnpauseProposal"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "inTransitSince"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "oracleActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracleUpdateCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleUpdateHasApproved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleUpdateProposalCancelled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleUpdateProposalExpiresAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleUpdateProposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint, string, boolean] & {
        newOracle: string;
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        eta: bigint;
        proposer: string;
        emergencyFastTrack: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposeAddAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeDisputeSolution"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, _disputeStatus: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeOracleUpdate"
  ): TypedContractMethod<[_newOracle: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeUnpause"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "refundInTransitAfterTimeout"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFundsStage1"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalClaimableUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tradeActiveDisputeProposalId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tradeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tradeHasActiveDisputeProposal"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tradeId: bigint;
        ricardianHash: string;
        status: bigint;
        buyerAddress: string;
        supplierAddress: string;
        totalAmountLocked: bigint;
        logisticsAmount: bigint;
        platformFeesAmount: bigint;
        supplierFirstTranche: bigint;
        supplierSecondTranche: bigint;
        createdAt: bigint;
        arrivalTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpauseHasApproved"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpauseProposal"
  ): TypedContractMethod<
    [],
    [
      [bigint, boolean, bigint, string] & {
        approvalCount: bigint;
        executed: boolean;
        createdAt: bigint;
        proposer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AdminAddApproved"
  ): TypedContractEvent<
    AdminAddApprovedEvent.InputTuple,
    AdminAddApprovedEvent.OutputTuple,
    AdminAddApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AdminAddProposalExpiredCancelled"
  ): TypedContractEvent<
    AdminAddProposalExpiredCancelledEvent.InputTuple,
    AdminAddProposalExpiredCancelledEvent.OutputTuple,
    AdminAddProposalExpiredCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AdminAddProposed"
  ): TypedContractEvent<
    AdminAddProposedEvent.InputTuple,
    AdminAddProposedEvent.OutputTuple,
    AdminAddProposedEvent.OutputObject
  >;
  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "ArrivalConfirmed"
  ): TypedContractEvent<
    ArrivalConfirmedEvent.InputTuple,
    ArrivalConfirmedEvent.OutputTuple,
    ArrivalConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimableAccrued"
  ): TypedContractEvent<
    ClaimableAccruedEvent.InputTuple,
    ClaimableAccruedEvent.OutputTuple,
    ClaimableAccruedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeApproved"
  ): TypedContractEvent<
    DisputeApprovedEvent.InputTuple,
    DisputeApprovedEvent.OutputTuple,
    DisputeApprovedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeFinalized"
  ): TypedContractEvent<
    DisputeFinalizedEvent.InputTuple,
    DisputeFinalizedEvent.OutputTuple,
    DisputeFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpenedByBuyer"
  ): TypedContractEvent<
    DisputeOpenedByBuyerEvent.InputTuple,
    DisputeOpenedByBuyerEvent.OutputTuple,
    DisputeOpenedByBuyerEvent.OutputObject
  >;
  getEvent(
    key: "DisputePayout"
  ): TypedContractEvent<
    DisputePayoutEvent.InputTuple,
    DisputePayoutEvent.OutputTuple,
    DisputePayoutEvent.OutputObject
  >;
  getEvent(
    key: "DisputeProposalExpiredCancelled"
  ): TypedContractEvent<
    DisputeProposalExpiredCancelledEvent.InputTuple,
    DisputeProposalExpiredCancelledEvent.OutputTuple,
    DisputeProposalExpiredCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DisputeSolutionProposed"
  ): TypedContractEvent<
    DisputeSolutionProposedEvent.InputTuple,
    DisputeSolutionProposedEvent.OutputTuple,
    DisputeSolutionProposedEvent.OutputObject
  >;
  getEvent(
    key: "FinalTrancheReleased"
  ): TypedContractEvent<
    FinalTrancheReleasedEvent.InputTuple,
    FinalTrancheReleasedEvent.OutputTuple,
    FinalTrancheReleasedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleasedStage1"
  ): TypedContractEvent<
    FundsReleasedStage1Event.InputTuple,
    FundsReleasedStage1Event.OutputTuple,
    FundsReleasedStage1Event.OutputObject
  >;
  getEvent(
    key: "FundsReleasedStage2"
  ): TypedContractEvent<
    FundsReleasedStage2Event.InputTuple,
    FundsReleasedStage2Event.OutputTuple,
    FundsReleasedStage2Event.OutputObject
  >;
  getEvent(
    key: "InTransitTimeoutRefunded"
  ): TypedContractEvent<
    InTransitTimeoutRefundedEvent.InputTuple,
    InTransitTimeoutRefundedEvent.OutputTuple,
    InTransitTimeoutRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OracleDisabledEmergency"
  ): TypedContractEvent<
    OracleDisabledEmergencyEvent.InputTuple,
    OracleDisabledEmergencyEvent.OutputTuple,
    OracleDisabledEmergencyEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdateApproved"
  ): TypedContractEvent<
    OracleUpdateApprovedEvent.InputTuple,
    OracleUpdateApprovedEvent.OutputTuple,
    OracleUpdateApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdateProposalExpiredCancelled"
  ): TypedContractEvent<
    OracleUpdateProposalExpiredCancelledEvent.InputTuple,
    OracleUpdateProposalExpiredCancelledEvent.OutputTuple,
    OracleUpdateProposalExpiredCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdateProposed"
  ): TypedContractEvent<
    OracleUpdateProposedEvent.InputTuple,
    OracleUpdateProposedEvent.OutputTuple,
    OracleUpdateProposedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeesPaidStage1"
  ): TypedContractEvent<
    PlatformFeesPaidStage1Event.InputTuple,
    PlatformFeesPaidStage1Event.OutputTuple,
    PlatformFeesPaidStage1Event.OutputObject
  >;
  getEvent(
    key: "TradeCancelledAfterLockTimeout"
  ): TypedContractEvent<
    TradeCancelledAfterLockTimeoutEvent.InputTuple,
    TradeCancelledAfterLockTimeoutEvent.OutputTuple,
    TradeCancelledAfterLockTimeoutEvent.OutputObject
  >;
  getEvent(
    key: "TradeLocked"
  ): TypedContractEvent<
    TradeLockedEvent.InputTuple,
    TradeLockedEvent.OutputTuple,
    TradeLockedEvent.OutputObject
  >;
  getEvent(
    key: "UnpauseApproved"
  ): TypedContractEvent<
    UnpauseApprovedEvent.InputTuple,
    UnpauseApprovedEvent.OutputTuple,
    UnpauseApprovedEvent.OutputObject
  >;
  getEvent(
    key: "UnpauseProposalCancelled"
  ): TypedContractEvent<
    UnpauseProposalCancelledEvent.InputTuple,
    UnpauseProposalCancelledEvent.OutputTuple,
    UnpauseProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "UnpauseProposed"
  ): TypedContractEvent<
    UnpauseProposedEvent.InputTuple,
    UnpauseProposedEvent.OutputTuple,
    UnpauseProposedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AdminAddApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      AdminAddApprovedEvent.InputTuple,
      AdminAddApprovedEvent.OutputTuple,
      AdminAddApprovedEvent.OutputObject
    >;
    AdminAddApproved: TypedContractEvent<
      AdminAddApprovedEvent.InputTuple,
      AdminAddApprovedEvent.OutputTuple,
      AdminAddApprovedEvent.OutputObject
    >;

    "AdminAddProposalExpiredCancelled(uint256,address)": TypedContractEvent<
      AdminAddProposalExpiredCancelledEvent.InputTuple,
      AdminAddProposalExpiredCancelledEvent.OutputTuple,
      AdminAddProposalExpiredCancelledEvent.OutputObject
    >;
    AdminAddProposalExpiredCancelled: TypedContractEvent<
      AdminAddProposalExpiredCancelledEvent.InputTuple,
      AdminAddProposalExpiredCancelledEvent.OutputTuple,
      AdminAddProposalExpiredCancelledEvent.OutputObject
    >;

    "AdminAddProposed(uint256,address,address,uint256)": TypedContractEvent<
      AdminAddProposedEvent.InputTuple,
      AdminAddProposedEvent.OutputTuple,
      AdminAddProposedEvent.OutputObject
    >;
    AdminAddProposed: TypedContractEvent<
      AdminAddProposedEvent.InputTuple,
      AdminAddProposedEvent.OutputTuple,
      AdminAddProposedEvent.OutputObject
    >;

    "AdminAdded(address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "ArrivalConfirmed(uint256,uint256)": TypedContractEvent<
      ArrivalConfirmedEvent.InputTuple,
      ArrivalConfirmedEvent.OutputTuple,
      ArrivalConfirmedEvent.OutputObject
    >;
    ArrivalConfirmed: TypedContractEvent<
      ArrivalConfirmedEvent.InputTuple,
      ArrivalConfirmedEvent.OutputTuple,
      ArrivalConfirmedEvent.OutputObject
    >;

    "ClaimableAccrued(uint256,address,uint256,uint8)": TypedContractEvent<
      ClaimableAccruedEvent.InputTuple,
      ClaimableAccruedEvent.OutputTuple,
      ClaimableAccruedEvent.OutputObject
    >;
    ClaimableAccrued: TypedContractEvent<
      ClaimableAccruedEvent.InputTuple,
      ClaimableAccruedEvent.OutputTuple,
      ClaimableAccruedEvent.OutputObject
    >;

    "Claimed(address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "DisputeApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      DisputeApprovedEvent.InputTuple,
      DisputeApprovedEvent.OutputTuple,
      DisputeApprovedEvent.OutputObject
    >;
    DisputeApproved: TypedContractEvent<
      DisputeApprovedEvent.InputTuple,
      DisputeApprovedEvent.OutputTuple,
      DisputeApprovedEvent.OutputObject
    >;

    "DisputeFinalized(uint256,uint256,uint8)": TypedContractEvent<
      DisputeFinalizedEvent.InputTuple,
      DisputeFinalizedEvent.OutputTuple,
      DisputeFinalizedEvent.OutputObject
    >;
    DisputeFinalized: TypedContractEvent<
      DisputeFinalizedEvent.InputTuple,
      DisputeFinalizedEvent.OutputTuple,
      DisputeFinalizedEvent.OutputObject
    >;

    "DisputeOpenedByBuyer(uint256)": TypedContractEvent<
      DisputeOpenedByBuyerEvent.InputTuple,
      DisputeOpenedByBuyerEvent.OutputTuple,
      DisputeOpenedByBuyerEvent.OutputObject
    >;
    DisputeOpenedByBuyer: TypedContractEvent<
      DisputeOpenedByBuyerEvent.InputTuple,
      DisputeOpenedByBuyerEvent.OutputTuple,
      DisputeOpenedByBuyerEvent.OutputObject
    >;

    "DisputePayout(uint256,uint256,address,uint256,uint8)": TypedContractEvent<
      DisputePayoutEvent.InputTuple,
      DisputePayoutEvent.OutputTuple,
      DisputePayoutEvent.OutputObject
    >;
    DisputePayout: TypedContractEvent<
      DisputePayoutEvent.InputTuple,
      DisputePayoutEvent.OutputTuple,
      DisputePayoutEvent.OutputObject
    >;

    "DisputeProposalExpiredCancelled(uint256,uint256,address)": TypedContractEvent<
      DisputeProposalExpiredCancelledEvent.InputTuple,
      DisputeProposalExpiredCancelledEvent.OutputTuple,
      DisputeProposalExpiredCancelledEvent.OutputObject
    >;
    DisputeProposalExpiredCancelled: TypedContractEvent<
      DisputeProposalExpiredCancelledEvent.InputTuple,
      DisputeProposalExpiredCancelledEvent.OutputTuple,
      DisputeProposalExpiredCancelledEvent.OutputObject
    >;

    "DisputeSolutionProposed(uint256,uint256,uint8,address)": TypedContractEvent<
      DisputeSolutionProposedEvent.InputTuple,
      DisputeSolutionProposedEvent.OutputTuple,
      DisputeSolutionProposedEvent.OutputObject
    >;
    DisputeSolutionProposed: TypedContractEvent<
      DisputeSolutionProposedEvent.InputTuple,
      DisputeSolutionProposedEvent.OutputTuple,
      DisputeSolutionProposedEvent.OutputObject
    >;

    "FinalTrancheReleased(uint256,address,uint256)": TypedContractEvent<
      FinalTrancheReleasedEvent.InputTuple,
      FinalTrancheReleasedEvent.OutputTuple,
      FinalTrancheReleasedEvent.OutputObject
    >;
    FinalTrancheReleased: TypedContractEvent<
      FinalTrancheReleasedEvent.InputTuple,
      FinalTrancheReleasedEvent.OutputTuple,
      FinalTrancheReleasedEvent.OutputObject
    >;

    "FundsReleasedStage1(uint256,address,uint256,address,uint256)": TypedContractEvent<
      FundsReleasedStage1Event.InputTuple,
      FundsReleasedStage1Event.OutputTuple,
      FundsReleasedStage1Event.OutputObject
    >;
    FundsReleasedStage1: TypedContractEvent<
      FundsReleasedStage1Event.InputTuple,
      FundsReleasedStage1Event.OutputTuple,
      FundsReleasedStage1Event.OutputObject
    >;

    "FundsReleasedStage2(uint256,address,uint256,address,uint256)": TypedContractEvent<
      FundsReleasedStage2Event.InputTuple,
      FundsReleasedStage2Event.OutputTuple,
      FundsReleasedStage2Event.OutputObject
    >;
    FundsReleasedStage2: TypedContractEvent<
      FundsReleasedStage2Event.InputTuple,
      FundsReleasedStage2Event.OutputTuple,
      FundsReleasedStage2Event.OutputObject
    >;

    "InTransitTimeoutRefunded(uint256,address,uint256)": TypedContractEvent<
      InTransitTimeoutRefundedEvent.InputTuple,
      InTransitTimeoutRefundedEvent.OutputTuple,
      InTransitTimeoutRefundedEvent.OutputObject
    >;
    InTransitTimeoutRefunded: TypedContractEvent<
      InTransitTimeoutRefundedEvent.InputTuple,
      InTransitTimeoutRefundedEvent.OutputTuple,
      InTransitTimeoutRefundedEvent.OutputObject
    >;

    "OracleDisabledEmergency(address,address)": TypedContractEvent<
      OracleDisabledEmergencyEvent.InputTuple,
      OracleDisabledEmergencyEvent.OutputTuple,
      OracleDisabledEmergencyEvent.OutputObject
    >;
    OracleDisabledEmergency: TypedContractEvent<
      OracleDisabledEmergencyEvent.InputTuple,
      OracleDisabledEmergencyEvent.OutputTuple,
      OracleDisabledEmergencyEvent.OutputObject
    >;

    "OracleUpdateApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      OracleUpdateApprovedEvent.InputTuple,
      OracleUpdateApprovedEvent.OutputTuple,
      OracleUpdateApprovedEvent.OutputObject
    >;
    OracleUpdateApproved: TypedContractEvent<
      OracleUpdateApprovedEvent.InputTuple,
      OracleUpdateApprovedEvent.OutputTuple,
      OracleUpdateApprovedEvent.OutputObject
    >;

    "OracleUpdateProposalExpiredCancelled(uint256,address)": TypedContractEvent<
      OracleUpdateProposalExpiredCancelledEvent.InputTuple,
      OracleUpdateProposalExpiredCancelledEvent.OutputTuple,
      OracleUpdateProposalExpiredCancelledEvent.OutputObject
    >;
    OracleUpdateProposalExpiredCancelled: TypedContractEvent<
      OracleUpdateProposalExpiredCancelledEvent.InputTuple,
      OracleUpdateProposalExpiredCancelledEvent.OutputTuple,
      OracleUpdateProposalExpiredCancelledEvent.OutputObject
    >;

    "OracleUpdateProposed(uint256,address,address,uint256,bool)": TypedContractEvent<
      OracleUpdateProposedEvent.InputTuple,
      OracleUpdateProposedEvent.OutputTuple,
      OracleUpdateProposedEvent.OutputObject
    >;
    OracleUpdateProposed: TypedContractEvent<
      OracleUpdateProposedEvent.InputTuple,
      OracleUpdateProposedEvent.OutputTuple,
      OracleUpdateProposedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeesPaidStage1(uint256,address,uint256)": TypedContractEvent<
      PlatformFeesPaidStage1Event.InputTuple,
      PlatformFeesPaidStage1Event.OutputTuple,
      PlatformFeesPaidStage1Event.OutputObject
    >;
    PlatformFeesPaidStage1: TypedContractEvent<
      PlatformFeesPaidStage1Event.InputTuple,
      PlatformFeesPaidStage1Event.OutputTuple,
      PlatformFeesPaidStage1Event.OutputObject
    >;

    "TradeCancelledAfterLockTimeout(uint256,address,uint256)": TypedContractEvent<
      TradeCancelledAfterLockTimeoutEvent.InputTuple,
      TradeCancelledAfterLockTimeoutEvent.OutputTuple,
      TradeCancelledAfterLockTimeoutEvent.OutputObject
    >;
    TradeCancelledAfterLockTimeout: TypedContractEvent<
      TradeCancelledAfterLockTimeoutEvent.InputTuple,
      TradeCancelledAfterLockTimeoutEvent.OutputTuple,
      TradeCancelledAfterLockTimeoutEvent.OutputObject
    >;

    "TradeLocked(uint256,address,address,uint256,uint256,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      TradeLockedEvent.InputTuple,
      TradeLockedEvent.OutputTuple,
      TradeLockedEvent.OutputObject
    >;
    TradeLocked: TypedContractEvent<
      TradeLockedEvent.InputTuple,
      TradeLockedEvent.OutputTuple,
      TradeLockedEvent.OutputObject
    >;

    "UnpauseApproved(address,uint256,uint256)": TypedContractEvent<
      UnpauseApprovedEvent.InputTuple,
      UnpauseApprovedEvent.OutputTuple,
      UnpauseApprovedEvent.OutputObject
    >;
    UnpauseApproved: TypedContractEvent<
      UnpauseApprovedEvent.InputTuple,
      UnpauseApprovedEvent.OutputTuple,
      UnpauseApprovedEvent.OutputObject
    >;

    "UnpauseProposalCancelled(address)": TypedContractEvent<
      UnpauseProposalCancelledEvent.InputTuple,
      UnpauseProposalCancelledEvent.OutputTuple,
      UnpauseProposalCancelledEvent.OutputObject
    >;
    UnpauseProposalCancelled: TypedContractEvent<
      UnpauseProposalCancelledEvent.InputTuple,
      UnpauseProposalCancelledEvent.OutputTuple,
      UnpauseProposalCancelledEvent.OutputObject
    >;

    "UnpauseProposed(address)": TypedContractEvent<
      UnpauseProposedEvent.InputTuple,
      UnpauseProposedEvent.OutputTuple,
      UnpauseProposedEvent.OutputObject
    >;
    UnpauseProposed: TypedContractEvent<
      UnpauseProposedEvent.InputTuple,
      UnpauseProposedEvent.OutputTuple,
      UnpauseProposedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
