/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agroasysEscrowSol from "./AgroasysEscrow.sol";
export type { agroasysEscrowSol };
import type * as test from "./test";
export type { test };
export type { MockUSDC } from "./MockUSDC";
