module.exports = class Data1771180205323 {
    name = 'Data1771180205323'

    async up(db) {
        await db.query(`CREATE TABLE "trade_event" ("id" character varying NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "extrinsic_index" integer NOT NULL, "total_amount" numeric, "logistics_amount" numeric, "platform_fees_amount" numeric, "supplier_first_tranche" numeric, "supplier_second_tranche" numeric, "released_first_tranche" numeric, "released_logistics_amount" numeric, "treasury_address" text, "paid_platform_fees" numeric, "arrival_timestamp" numeric, "final_tranche" numeric, "final_recipient" text, "refunded_amount" numeric, "refunded_to" text, "refunded_buyer_principal" numeric, "payout_recipient" text, "payout_amount" numeric, "payout_type" character varying(7), "related_proposal_id" text, "trade_id" character varying, CONSTRAINT "PK_728d9646fc0b297fd53619fa5e5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3408756ee41eca556530a91ad2" ON "trade_event" ("trade_id") `)
        await db.query(`CREATE INDEX "IDX_4c9748fae6f5f59c1de6e58b51" ON "trade_event" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_0bb2252e05d25479c61146ae09" ON "trade_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_87c7d58fbe023190ca9eecb0cb" ON "trade_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_4014c30eb00731b6364e6c6efc" ON "trade_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "dispute_event" ("id" character varying NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "extrinsic_index" integer NOT NULL, "proposed_dispute_status" character varying(7), "proposer" text, "approver" text, "approval_count" integer, "required_approvals" integer, "final_dispute_status" character varying(7), "cancelled_by" text, "dispute_id" character varying, CONSTRAINT "PK_45f1a5ccb8f7a2437ff8909b71f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_200ec7dc1960be051ff71d76ec" ON "dispute_event" ("dispute_id") `)
        await db.query(`CREATE INDEX "IDX_e34549cac569bea884689106d7" ON "dispute_event" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_263c9cc77964813ce94eb94a5c" ON "dispute_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_d5185a877252bfc0c7a670af80" ON "dispute_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_50aadabeafc26d1e3f1531db30" ON "dispute_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "dispute_proposal" ("id" character varying NOT NULL, "proposal_id" text NOT NULL, "dispute_status" character varying(7) NOT NULL, "approval_count" integer NOT NULL, "executed" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "proposer" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "cancelled" boolean NOT NULL, "trade_id" character varying, CONSTRAINT "PK_bfd7c0b2df03d36d6be8cf84486" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_28d091b79b2846932318e70717" ON "dispute_proposal" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_49a5da33a65902441b67111348" ON "dispute_proposal" ("trade_id") `)
        await db.query(`CREATE INDEX "IDX_0cb8e7fa69edcce40c10075e8d" ON "dispute_proposal" ("dispute_status") `)
        await db.query(`CREATE INDEX "IDX_a05d3e232bcb5ba768c75a33b7" ON "dispute_proposal" ("executed") `)
        await db.query(`CREATE INDEX "IDX_4313798e226ae54cc2411092cb" ON "dispute_proposal" ("created_at") `)
        await db.query(`CREATE INDEX "IDX_6644f30afe3bc93f2b39387799" ON "dispute_proposal" ("proposer") `)
        await db.query(`CREATE INDEX "IDX_cfb0032c3e44b04a9e9e34d970" ON "dispute_proposal" ("cancelled") `)
        await db.query(`CREATE TABLE "trade" ("id" character varying NOT NULL, "trade_id" text NOT NULL, "buyer" text NOT NULL, "supplier" text NOT NULL, "status" character varying(17) NOT NULL, "total_amount_locked" numeric NOT NULL, "logistics_amount" numeric NOT NULL, "platform_fees_amount" numeric NOT NULL, "supplier_first_tranche" numeric NOT NULL, "supplier_second_tranche" numeric NOT NULL, "ricardian_hash" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "arrival_timestamp" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d4097908741dc408f8274ebdc53" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_db4539cb8962bc3722950ebf19" ON "trade" ("trade_id") `)
        await db.query(`CREATE INDEX "IDX_cfb8d86a3f28435445e132a2dc" ON "trade" ("buyer") `)
        await db.query(`CREATE INDEX "IDX_32ee6fe694d94ee5834c17a3b5" ON "trade" ("supplier") `)
        await db.query(`CREATE INDEX "IDX_85f0c92d4a133135aafce952df" ON "trade" ("status") `)
        await db.query(`CREATE INDEX "IDX_1fa8b882815c66af40b4194894" ON "trade" ("created_at") `)
        await db.query(`CREATE TABLE "oracle_event" ("id" character varying NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "extrinsic_index" integer NOT NULL, "proposed_oracle" text, "eta" numeric, "proposer" text, "approver" text, "approval_count" integer, "required_approvals" integer, "old_oracle" text, "new_oracle" text, "cancelled_by" text, "disabled_by" text, "previous_oracle" text, "oracle_update_id" character varying, CONSTRAINT "PK_25e19d364e5a1bd428bb2382acc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6332b67418267dcc642fc8fc1f" ON "oracle_event" ("oracle_update_id") `)
        await db.query(`CREATE INDEX "IDX_377cbe80128aa963a248625a2a" ON "oracle_event" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_0276b467d28174e42a50b66a46" ON "oracle_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_d3aee13582e31c510ee68e45b1" ON "oracle_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_fd2632ad10d26dbf92f39b6f6a" ON "oracle_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "oracle_update_proposal" ("id" character varying NOT NULL, "proposal_id" text NOT NULL, "new_oracle" text NOT NULL, "approval_count" integer NOT NULL, "executed" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "eta" numeric NOT NULL, "proposer" text NOT NULL, "emergency_fast_track" boolean, "expires_at" TIMESTAMP WITH TIME ZONE, "cancelled" boolean NOT NULL, CONSTRAINT "PK_7b7c1d4d793fd1804e03c125a67" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f1ac95f00d711d551d47fc9819" ON "oracle_update_proposal" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_df6cb9f02d31df89bdcf4727c5" ON "oracle_update_proposal" ("new_oracle") `)
        await db.query(`CREATE INDEX "IDX_b6477a91ef1d45a9f1b94b26c2" ON "oracle_update_proposal" ("executed") `)
        await db.query(`CREATE INDEX "IDX_30b9cba9875823b4d8fcda9f50" ON "oracle_update_proposal" ("created_at") `)
        await db.query(`CREATE INDEX "IDX_f469b881a00d99bc58fe007d25" ON "oracle_update_proposal" ("proposer") `)
        await db.query(`CREATE INDEX "IDX_801b582a337d1ae7718fc92ad2" ON "oracle_update_proposal" ("cancelled") `)
        await db.query(`CREATE TABLE "admin_event" ("id" character varying NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "extrinsic_index" integer NOT NULL, "proposed_admin" text, "eta" numeric, "proposer" text, "approver" text, "approval_count" integer, "required_approvals" integer, "added_admin" text, "cancelled_by" text, "admin_add_proposal_id" character varying, CONSTRAINT "PK_a398007162da57a4a17c21fe4ed" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d3b69d887e7be85ab626c070a3" ON "admin_event" ("admin_add_proposal_id") `)
        await db.query(`CREATE INDEX "IDX_5b067a6dc700e79b999d0a0077" ON "admin_event" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_42d7518deb7ef536f2a109d0c3" ON "admin_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_2a62f6ee47e2b575f1a518cca0" ON "admin_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_fdc3a035fa205ba96010b6f274" ON "admin_event" ("tx_hash") `)
        await db.query(`CREATE TABLE "admin_add_proposal" ("id" character varying NOT NULL, "proposal_id" text NOT NULL, "new_admin" text NOT NULL, "approval_count" integer NOT NULL, "executed" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "eta" numeric NOT NULL, "proposer" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "cancelled" boolean NOT NULL, CONSTRAINT "PK_1a0a8da5c7926e655a2ab8e5494" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4328a92b800b40e83cae23b28b" ON "admin_add_proposal" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_67ed5d03e6ad978f66a8bc837e" ON "admin_add_proposal" ("new_admin") `)
        await db.query(`CREATE INDEX "IDX_a352b788506f1bde6387658fa3" ON "admin_add_proposal" ("executed") `)
        await db.query(`CREATE INDEX "IDX_83b312e4cde8a32aa1aeba67d0" ON "admin_add_proposal" ("created_at") `)
        await db.query(`CREATE INDEX "IDX_6f568395738a583a6d4464317b" ON "admin_add_proposal" ("proposer") `)
        await db.query(`CREATE INDEX "IDX_4312e3977304fa06b6b8f3d422" ON "admin_add_proposal" ("cancelled") `)
        await db.query(`CREATE TABLE "system_event" ("id" character varying NOT NULL, "event_name" text NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "extrinsic_index" integer NOT NULL, "triggered_by" text, CONSTRAINT "PK_387d2d01bb48af5099e53bd14cf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7ff7d829541d61c592e9e5c196" ON "system_event" ("event_name") `)
        await db.query(`CREATE INDEX "IDX_82d04998f89102e75dc9c4d074" ON "system_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_252506670ac8dc8e24bb154961" ON "system_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_1ba591704beabb03a9731beff0" ON "system_event" ("tx_hash") `)
        await db.query(`ALTER TABLE "trade_event" ADD CONSTRAINT "FK_3408756ee41eca556530a91ad2b" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "dispute_event" ADD CONSTRAINT "FK_200ec7dc1960be051ff71d76ecd" FOREIGN KEY ("dispute_id") REFERENCES "dispute_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "dispute_proposal" ADD CONSTRAINT "FK_49a5da33a65902441b67111348f" FOREIGN KEY ("trade_id") REFERENCES "trade"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "oracle_event" ADD CONSTRAINT "FK_6332b67418267dcc642fc8fc1fa" FOREIGN KEY ("oracle_update_id") REFERENCES "oracle_update_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "admin_event" ADD CONSTRAINT "FK_d3b69d887e7be85ab626c070a3d" FOREIGN KEY ("admin_add_proposal_id") REFERENCES "admin_add_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE IF EXISTS "trade_event" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "dispute_event" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "oracle_event" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "admin_event" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "system_event" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "dispute_proposal" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "oracle_update_proposal" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "admin_add_proposal" CASCADE`)
        await db.query(`DROP TABLE IF EXISTS "trade" CASCADE`)
    }
}
