/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as claimSecurityFixturesSol from "./ClaimSecurityFixtures.sol";
export type { claimSecurityFixturesSol };
