import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildReconciliationReport,
  buildReconciliationReportRows,
  RECONCILIATION_REPORT_VERSION,
} from '../core/reconciliationReport';

test('reconciliation report rows are deterministically ordered and keep stable schema fields', () => {
  const rows = buildReconciliationReportRows(
    [
      {
        tradeId: '10',
        txHash: '0xbb',
        payoutState: 'PENDING_REVIEW',
        accountingState: 'REALIZED',
        accountingStateReason: 'Controlled revenue realization recorded',
        accountingPeriodKey: '2026-Q1',
        accountingPeriodStatus: 'OPEN',
        sweepBatchId: 12,
        sweepBatchStatus: 'CLOSED',
        matchedSweepTxHash: '0xsweep-b',
        matchedSweptAt: new Date('2026-03-25T01:30:00.000Z'),
        partnerName: 'partner-b',
        partnerReference: 'partner-ref-b',
        partnerHandoffStatus: 'COMPLETED',
        realizedAt: new Date('2026-03-25T06:00:00.000Z'),
        rampReference: 'ramp-b',
        fiatDepositState: 'PARTIAL',
        fiatDepositFailureClass: 'PARTIAL_FUNDING',
        fiatDepositObservedAt: new Date('2026-03-25T00:00:00.000Z'),
        bankReference: 'bank-b',
        bankPayoutState: 'CONFIRMED',
        bankFailureCode: null,
        bankConfirmedAt: new Date('2026-03-25T02:00:00.000Z'),
        mismatchCodes: ['STATUS_MISMATCH', 'STATUS_MISMATCH', 'HASH_MISMATCH'],
        ledgerEntryId: 4,
      },
      {
        tradeId: '2',
        txHash: null,
        payoutState: null,
        accountingState: null,
        accountingStateReason: null,
        accountingPeriodKey: null,
        accountingPeriodStatus: null,
        sweepBatchId: null,
        sweepBatchStatus: null,
        matchedSweepTxHash: null,
        matchedSweptAt: null,
        partnerName: null,
        partnerReference: null,
        partnerHandoffStatus: null,
        realizedAt: null,
        rampReference: 'ramp-a',
        fiatDepositState: 'PENDING',
        fiatDepositFailureClass: null,
        fiatDepositObservedAt: new Date('2026-03-24T00:00:00.000Z'),
        bankReference: null,
        bankPayoutState: null,
        bankFailureCode: null,
        bankConfirmedAt: null,
        mismatchCodes: ['ONCHAIN_READ_ERROR'],
        ledgerEntryId: null,
      },
      {
        tradeId: '10',
        txHash: '0xaa',
        payoutState: 'EXTERNAL_EXECUTION_CONFIRMED',
        accountingState: 'HANDED_OFF',
        accountingStateReason: 'External handoff acknowledged by execution counterparty',
        accountingPeriodKey: '2026-Q1',
        accountingPeriodStatus: 'OPEN',
        sweepBatchId: 11,
        sweepBatchStatus: 'HANDED_OFF',
        matchedSweepTxHash: '0xsweep-a',
        matchedSweptAt: new Date('2026-03-26T02:30:00.000Z'),
        partnerName: 'partner-a',
        partnerReference: 'partner-ref-a',
        partnerHandoffStatus: 'ACKNOWLEDGED',
        realizedAt: null,
        rampReference: 'ramp-a',
        fiatDepositState: 'FUNDED',
        fiatDepositFailureClass: null,
        fiatDepositObservedAt: new Date('2026-03-26T00:00:00.000Z'),
        bankReference: 'bank-a',
        bankPayoutState: 'PENDING',
        bankFailureCode: null,
        bankConfirmedAt: new Date('2026-03-26T04:00:00.000Z'),
        mismatchCodes: [],
        ledgerEntryId: 1,
      },
    ],
    { now: new Date('2026-03-26T12:00:00.000Z') },
  );

  assert.deepEqual(rows, [
    {
      tradeId: '2',
      txHash: null,
      payoutState: null,
      accountingState: null,
      accountingStateReason: null,
      accountingPeriodKey: null,
      accountingPeriodStatus: null,
      sweepBatchId: null,
      sweepBatchStatus: null,
      matchedSweepTxHash: null,
      matchedSweptAt: null,
      partnerName: null,
      partnerReference: null,
      partnerHandoffStatus: null,
      realizedAt: null,
      rampReference: 'ramp-a',
      fiatDepositState: 'PENDING',
      fiatDepositFailureReason: null,
      fiatDepositObservedAt: '2026-03-24T00:00:00.000Z',
      bankReference: null,
      bankPayoutState: null,
      bankFailureCode: null,
      bankConfirmedAt: null,
      bankPayoutDivergenceReason: null,
      reconciliationVerdict: 'MISMATCH',
      mismatchReason: 'ONCHAIN_READ_ERROR,STALE_PENDING_DEPOSIT',
    },
    {
      tradeId: '10',
      txHash: '0xaa',
      payoutState: 'EXTERNAL_EXECUTION_CONFIRMED',
      accountingState: 'HANDED_OFF',
      accountingStateReason: 'External handoff acknowledged by execution counterparty',
      accountingPeriodKey: '2026-Q1',
      accountingPeriodStatus: 'OPEN',
      sweepBatchId: 11,
      sweepBatchStatus: 'HANDED_OFF',
      matchedSweepTxHash: '0xsweep-a',
      matchedSweptAt: '2026-03-26T02:30:00.000Z',
      partnerName: 'partner-a',
      partnerReference: 'partner-ref-a',
      partnerHandoffStatus: 'ACKNOWLEDGED',
      realizedAt: null,
      rampReference: 'ramp-a',
      fiatDepositState: 'FUNDED',
      fiatDepositFailureReason: null,
      fiatDepositObservedAt: '2026-03-26T00:00:00.000Z',
      bankReference: 'bank-a',
      bankPayoutState: 'PENDING',
      bankFailureCode: null,
      bankConfirmedAt: '2026-03-26T04:00:00.000Z',
      bankPayoutDivergenceReason: 'TREASURY_BANK_STATE_DIVERGENCE',
      reconciliationVerdict: 'MISMATCH',
      mismatchReason: 'TREASURY_BANK_STATE_DIVERGENCE',
    },
    {
      tradeId: '10',
      txHash: '0xbb',
      payoutState: 'PENDING_REVIEW',
      accountingState: 'REALIZED',
      accountingStateReason: 'Controlled revenue realization recorded',
      accountingPeriodKey: '2026-Q1',
      accountingPeriodStatus: 'OPEN',
      sweepBatchId: 12,
      sweepBatchStatus: 'CLOSED',
      matchedSweepTxHash: '0xsweep-b',
      matchedSweptAt: '2026-03-25T01:30:00.000Z',
      partnerName: 'partner-b',
      partnerReference: 'partner-ref-b',
      partnerHandoffStatus: 'COMPLETED',
      realizedAt: '2026-03-25T06:00:00.000Z',
      rampReference: 'ramp-b',
      fiatDepositState: 'PARTIAL',
      fiatDepositFailureReason: 'PARTIAL_FUNDING',
      fiatDepositObservedAt: '2026-03-25T00:00:00.000Z',
      bankReference: 'bank-b',
      bankPayoutState: 'CONFIRMED',
      bankFailureCode: null,
      bankConfirmedAt: '2026-03-25T02:00:00.000Z',
      bankPayoutDivergenceReason: 'TREASURY_BANK_STATE_DIVERGENCE',
      reconciliationVerdict: 'MISMATCH',
      mismatchReason:
        'HASH_MISMATCH,PARTIAL_FUNDING,STATUS_MISMATCH,TREASURY_BANK_STATE_DIVERGENCE',
    },
  ]);
});

test('reconciliation report summary counts are stable', () => {
  const report = buildReconciliationReport('once-2026-03-01T00:00:00.000Z', [
    {
      tradeId: '1',
      txHash: '0xabc',
      payoutState: 'EXTERNAL_EXECUTION_CONFIRMED',
      accountingState: 'REALIZED',
      accountingStateReason: 'Controlled revenue realization recorded',
      accountingPeriodKey: '2026-Q1',
      accountingPeriodStatus: 'CLOSED',
      sweepBatchId: 1,
      sweepBatchStatus: 'CLOSED',
      matchedSweepTxHash: '0xsweep-1',
      matchedSweptAt: new Date('2026-03-01T00:30:00.000Z'),
      partnerName: 'partner-1',
      partnerReference: 'partner-ref-1',
      partnerHandoffStatus: 'COMPLETED',
      realizedAt: new Date('2026-03-01T01:30:00.000Z'),
      rampReference: 'ramp-1',
      fiatDepositState: 'FUNDED',
      fiatDepositFailureClass: null,
      fiatDepositObservedAt: new Date('2026-03-01T00:00:00.000Z'),
      bankReference: 'bank-1',
      bankPayoutState: 'CONFIRMED',
      bankFailureCode: null,
      bankConfirmedAt: new Date('2026-03-01T01:00:00.000Z'),
      mismatchCodes: [],
      ledgerEntryId: 1,
    },
    {
      tradeId: '2',
      txHash: null,
      payoutState: null,
      accountingState: null,
      accountingStateReason: null,
      accountingPeriodKey: null,
      accountingPeriodStatus: null,
      sweepBatchId: null,
      sweepBatchStatus: null,
      matchedSweepTxHash: null,
      matchedSweptAt: null,
      partnerName: null,
      partnerReference: null,
      partnerHandoffStatus: null,
      realizedAt: null,
      rampReference: null,
      fiatDepositState: null,
      fiatDepositFailureClass: null,
      fiatDepositObservedAt: null,
      bankReference: null,
      bankPayoutState: null,
      bankFailureCode: null,
      bankConfirmedAt: null,
      mismatchCodes: ['AMOUNT_MISMATCH'],
      ledgerEntryId: null,
    },
  ]);

  assert.equal(report.reportVersion, RECONCILIATION_REPORT_VERSION);
  assert.equal(report.runKey, 'once-2026-03-01T00:00:00.000Z');
  assert.equal(report.summary.rowCount, 2);
  assert.equal(report.summary.matchCount, 1);
  assert.equal(report.summary.mismatchCount, 1);
});

test('allocated amount drift is surfaced as a deterministic mismatch', () => {
  const [row] = buildReconciliationReportRows([
    {
      tradeId: '1',
      txHash: '0xabc',
      payoutState: 'PENDING_REVIEW',
      sourceAmountRaw: '1000',
      allocatedAmountRaw: '900',
      accountingState: 'ALLOCATED_TO_SWEEP',
      accountingStateReason: 'Ledger entry is allocated to a sweep batch',
      accountingPeriodKey: '2026-Q2',
      accountingPeriodStatus: 'OPEN',
      sweepBatchId: 1,
      sweepBatchStatus: 'DRAFT',
      matchedSweepTxHash: null,
      matchedSweptAt: null,
      partnerName: null,
      partnerReference: null,
      partnerHandoffStatus: null,
      realizedAt: null,
      rampReference: null,
      fiatDepositState: null,
      fiatDepositFailureClass: null,
      fiatDepositObservedAt: null,
      bankReference: null,
      bankPayoutState: null,
      bankFailureCode: null,
      bankConfirmedAt: null,
      mismatchCodes: [],
      ledgerEntryId: 1,
    },
  ]);

  assert.equal(row.reconciliationVerdict, 'MISMATCH');
  assert.equal(row.mismatchReason, 'ALLOCATED_AMOUNT_DIFFERS_FROM_SOURCE');
});
