/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClaimableEscrow,
  IClaimableEscrowInterface,
} from "../../../../src/test/ClaimSecurityFixtures.sol/IClaimableEscrow";

const _abi = [
  {
    inputs: [],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClaimableEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimableEscrowInterface {
    return new Interface(_abi) as IClaimableEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClaimableEscrow {
    return new Contract(address, _abi, runner) as unknown as IClaimableEscrow;
  }
}
