/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenTransferHook,
  ITokenTransferHookInterface,
} from "../../../../src/test/ClaimSecurityFixtures.sol/ITokenTransferHook";

const _abi = [
  {
    inputs: [],
    name: "onTokenTransferHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenTransferHook__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenTransferHookInterface {
    return new Interface(_abi) as ITokenTransferHookInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenTransferHook {
    return new Contract(address, _abi, runner) as unknown as ITokenTransferHook;
  }
}
