/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasuryClaimEscrow,
  ITreasuryClaimEscrowInterface,
} from "../../../../src/test/ClaimSecurityFixtures.sol/ITreasuryClaimEscrow";

const _abi = [
  {
    inputs: [],
    name: "claimTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITreasuryClaimEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryClaimEscrowInterface {
    return new Interface(_abi) as ITreasuryClaimEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasuryClaimEscrow {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITreasuryClaimEscrow;
  }
}
