/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ClaimHookReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attackEnabled"
      | "configure"
      | "escrow"
      | "forceRevert"
      | "lastError"
      | "onTokenTransferHook"
      | "reentryAttempted"
      | "triggerTreasuryClaim"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attackEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [boolean, boolean]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forceRevert",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastError", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onTokenTransferHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentryAttempted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerTreasuryClaim",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "attackEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastError", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransferHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryAttempted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerTreasuryClaim",
    data: BytesLike
  ): Result;
}

export interface ClaimHookReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimHookReceiver;
  waitForDeployment(): Promise<this>;

  interface: ClaimHookReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attackEnabled: TypedContractMethod<[], [boolean], "view">;

  configure: TypedContractMethod<
    [_attackEnabled: boolean, _forceRevert: boolean],
    [void],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  forceRevert: TypedContractMethod<[], [boolean], "view">;

  lastError: TypedContractMethod<[], [string], "view">;

  onTokenTransferHook: TypedContractMethod<[], [void], "nonpayable">;

  reentryAttempted: TypedContractMethod<[], [boolean], "view">;

  triggerTreasuryClaim: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attackEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [_attackEnabled: boolean, _forceRevert: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forceRevert"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastError"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onTokenTransferHook"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reentryAttempted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "triggerTreasuryClaim"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
