[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc_version = "0.8.34"
via_ir = true

[fuzz]
runs = 200
depth = 500
fail_on_revert=false
